package org.exception.questions;

public class Q1 {

	public class Test {

	}

	public static void main(String[] args) {
		try {
			System.out.printf("1");
			int sum = 9 / 0;
			System.out.printf("2");
		} catch (ArithmeticException e) {
			System.out.printf("3");
			
			String s = "100r";
				int id = Integer.parseInt(s);
				System.out.println(id);
			
		}

		catch (Exception e) {
			System.out.printf("4");
			
			
		} finally {
			System.out.printf("5");
		}
	}
}
